@host=http://localhost:5256

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NTUxODJkMy1iYTZkLTRjOWQtYmI2MC0zNmU5ZWY5M2RhYjYiLCJnaXZlbl9uYW1lIjoiTWFzb3VkIiwiZmFtaWx5X25hbWUiOiJLaG9kYWRhZGkiLCJqdGkiOiI0M2ZmYTQ1Ni00MGJhLTQ2YTEtOTkzNS0xN2E0NDJlYThhYzgiLCJleHAiOjE3MDA2NTQxNTcsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.Asl0lKRknVwawp73KP8FKpKWUC7bPHeFnGgViS0L22o